{% set name = "floweaver" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2f7bb67af1a20137bbb05f95187d7f9be9c106b37e71650b71d6be0ac6276a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - pandas
    - networkx >=2.0
    - attrs
    - palettable

test:
  imports:
    - floweaver

about:
  home: http://github.com/ricklupton/floweaver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: View flow data as Sankey diagrams
  description: |
    Many kinds of data can be thought of as 'flows': energy and materials moving
    through industry, money flowing through the economy, telephone lines moving
    between providers, voters moving between parties. floWeaver helps you to
    exchange and analyse flow data and visualise it using Sankey diagrams.
  doc_url: https://floweaver.readthedocs.io/en/latest/
  dev_url: https://github.com/ricklupton/floweaver

extra:
  recipe-maintainers:
    - ricklupton
