travis:
  secure:
    BINSTAR_TOKEN: fJicLqr5xiQa2T1DkZ1q3Nf6r6fBkajuBUFchswm+Iv8R2pWi8DYfzmT1KM/xDa/wxF+qImTdAYmKPluMRV0C8H7N1dJrrS8KUU+eeDxcWEGdzAdJN34VNHH1Wb7ZzLG86HcWwTViNRVGFKpHj8kLHkxTfeThtUYqnvrnfDEatPQqXwsTmHukxrQg/CiWJy+3zOBU6nZqscJohwVlmub8XTeVdtDTOimhKDVqutWJr2/YGUZY9AeXgjUomSh3/cqiTltMY0XMAcstDY3vFbHH8SX6iBKNSREuvXhKBWbhk7Yl3RzeThaRIMasXHm07olZo6OXMQK1y4dbzub9v1GlDlcsACHU6CBXmX6TRzxjHtbiBl0Yd9Tyf5FgZC9w6gTd32FfMO13063ZurJsVQ3U5k/I3tabdVKvZCh5OhQ8u7SUjihkqkzZnuDkQDrxX99vYFwp0stRVT0Lp9E27eTphTmCEJXbjXAg0Ly4aoKxmCapczFRF7+JEpWNAxCMANHSprZCj35IPIhVzijTnV79+8RJGoe5/wUL/U8/IXmeTgKPprtAvj0eQ2PD8xumJ5oQ1uo3HsGq69lnv2L7gDPZlHR314bsqCML4gw9BTvdn5OsM1zzqr5HgcnnJ393q0Ixh5cuhJ8IGM7+wwS9XDOQ9oCcnXrR3kXsrkiKYrNooo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
